number1 = int(input("Enter Number 1: "))
number2 = int(input("Enter Number 2: "))

print(str(number1%number2))
print(str(number1+number2))
print(str(number1-number2))
print(str(number1*number2))
print(str(number1**number2))
print(str(number1/number2))
print(str(number1//number2))